/** Longer phrases first so "black tea" wins over "tea". */
export const SCENT_NOTE_TERMS = [
  'black tea',
  'orange blossom',
  'sea salt',
  'white florals',
  'soft amber',
  'amberwood',
  'sandalwood',
  'patchouli',
  'bergamot',
  'grapefruit',
  'mandarin',
  'cardamom',
  'cinnamon',
  'frangipani',
  'lavender',
  'vetiver',
  'ambergris',
  'ambroxan',
  'coconut',
  'vanilla',
  'jasmine',
  'neroli',
  'ginger',
  'incense',
  'leather',
  'cedar',
  'tonka',
  'musk',
  'amber',
  'violet',
  'peony',
  'iris',
  'rose',
  'oud',
  'fig',
  'pear',
  'lime',
  'lemon',
  'yuzu',
  'sage',
  'thyme',
  'basil',
  'smoke',
  'tea',
].sort((a, b) => b.length - a.length);

export const SCENT_STRUCTURE_TERMS = [
  'dry-down',
  'dry down',
  'opening',
  'projection',
  'sillage',
  'longevity',
  'heart',
  'base',
  'top',
].sort((a, b) => b.length - a.length);

export const SCENT_DESCRIPTOR_TERMS = [
  'tropical',
  'aromatic',
  'luxurious',
  'transparent',
  'gourmand',
  'aquatic',
  'soapy',
  'woody',
  'citrus',
  'floral',
  'fresh',
  'sweet',
  'warm',
  'dark',
  'clean',
  'airy',
  'dry',
  'green',
  'salty',
].sort((a, b) => b.length - a.length);
